name: deep_agent
description: Set up commands and instructions for Claude Code.
version: 0.0.18
repository: https://github.com/rezmeplxrf/deep_agent
topics:
  - cli
  - ai
  - llm
  - tool
environment:
  sdk: ^3.8.0

dependencies:
  args: ^2.7.0
  cli_completion: ^0.5.1
  collection: ^1.19.1
  mason_logger: ^0.3.3
  pub_updater: ^0.5.0

dev_dependencies:
  build_runner: ^2.4.15
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^1.0.4
  test: ^1.26.2
  very_good_analysis: ^9.0.0

platforms:
  linux:
  macos:
  windows:

executables:
  deep_agent:
